version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: tyma_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: tymashop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    container_name: tyma_backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:12341234@db:5432/tymashop
    ports:
      - '3010:3010'
    volumes:
      - ./backend:/app
    command: npm run start:dev

  frontend:
    build: ./frontend
    container_name: tyma_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend


volumes:
  postgres_data:
